[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[context.production.environment]
  REACT_APP_API_URL="https://europe-north1-quantum-enigma-454921-f7.cloudfunctions.net/my_portfolio_chat_entry_point/assistant"

[[redirects]]
  from = "https://www.hichamkhawand.com/*"
  to = "https://hichamkhawand.com/:splat"
  status = 301
  force = true